config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get :result, to: "home#result", as: :result
  delete :destroys, to: "home#destroys", as: :destroys
  post :update_number_of_option, to: "home#update_number_of_option", as: :update_number_of_option
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper

  def index
    @lucked_wheel_datas = read_data_random
    @number_of_options = number_of_option.to_i
  end

  def result 
    #number_of_options = read_data_general.to_i

    #random number
    # random_number = rand(number_of_options)

    # lucky_datas = read_data_random

    # while lucky_datas.include? random_number.to_s || random_number == 0 || random_number < 0
    #   random_number = rand(number_of_options)
    # end
    
    numbers = number_of_list

    unless numbers == nil || numbers.length == 0
    
      #random number
      random_number = numbers.sample

      #remove element in number_of_list
      numbers.delete(random_number)
      write_number_of_list(numbers)

      #write random data to new list
      write_data_random(random_number)
    end 

    @random_number = random_number
  end

  #delete
  def destroys
    clear_file_data
    redirect_to root_path
  end

  #post
  def update_number_of_option
    number = params["number"].to_i
    write_number_of_option(number)

    #clear all data
    clear_file_data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def number_of_option
        data = File.read(Rails.root.join("app/datas/number_of_options.txt"))
    end

    def number_of_list
        data = File.read(Rails.root.join("app/datas/numbers_list.txt")).split
    end

    def lucky_file
        file = Rails.root.join("app/datas/random_lucky.txt")
    end

    def read_data_random
        data = File.read(lucky_file).split
    end
    
    def write_number_of_option(number)
        path = Rails.root.join("app/datas/number_of_options.txt")
        File.write(path, number.to_s) 

        path_number_list = Rails.root.join("app/datas/numbers_list.txt")
        
        numbers = ''
        number.times do |num|
            numbers += (num + 1).to_s + " "
        end

        File.write(path_number_list, numbers) 
    end

    def write_number_of_list(numbers)
        path_number_list = Rails.root.join("app/datas/numbers_list.txt")
        
        list = ''
        numbers.each do |num|
            list += num.to_s + " "
        end

        File.write(path_number_list, list) 
    end

    def write_data_random(number)
        value = number.to_s + " "
        File.write(lucky_file, value, mode: "a")
    end

    def clear_file_data
        File.truncate(lucky_file, 0)
    end

    def audio_path(source, options = {})
        path_to_asset(source, {type: :audio}.merge!(options))
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_setting_modal.html.erb
<!-- Modal -->
  <div class="modal fade" id="setting" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"><i class="fa fa-wrench" aria-hidden="true"></i> Settings</h4>
        </div>
        <div class="modal-body">
          <%= form_with url: update_number_of_option_path, method: :post do |f| %>
            <div class="form-group">
                <label>Number of options </label>
                <%= f.number_field :number, class: 'form-control', value: @number_of_options || 200 %>
            </div>

            <div>
              <%= f.submit "Save", class: "btn btn-primary", id: "save" %>
            </div>
          <% end %>
        </div>
        
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/home/index.html.erb
<div class="text-right">
    <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#setting"><i class="fa fa-wrench"></i> Setting</button>
    <%= link_to "Reset data", destroys_path, method: :delete, class: "btn btn-danger btn-sm" %>
</div>

<div class="text-center image">
    <img src="/images/lucky_wheel.png">
</div>

<div class="text-center start-btn">
    <button class="btn btn-success start" >Start</button>

    <p>
       <a href="#" class="lucky-wheel-numbers">Hide lucky wheel numbers :</a><br>
       <span><%= @lucked_wheel_datas %></span>
    </p>

    <audio id="playaudio" src="/audios/start_game.mp3" controls loop hidden>
        <p>Your browser does not support HTML5 audio playback</p>
    </audio>
</div>

<%= render "setting_modal" %>

app/views/home/result.html.erb
<h1 class="result">
    <% if @random_number.to_i > 0 %>
        This is result....
        <strong><%= @random_number %></strong>
    <% else %>
        Out of range....
        <strong>The end!</strong>
    <% end %>
</h1>

<div class="text-center">
    <audio id="result-audio" src="/audios/result.mp3" autoplay controls hidden>
        <p>Your browser does not support HTML5 audio playback</p>
    </audio>
</div>

<div class="text-center start-btn">
    <%= link_to "Back", root_path, class: "btn btn-primary home-path" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lucky Wheel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="col-md-6 col-md-offset-3 lucky">
        <h1 class="main-title">Lucky Wheel</h1>
        <hr>
        <%= yield %>
      </div>
    </div>
  </body>
</html>